# Generated by Django 4.2.6 on 2023-11-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_conservation_link_img_alter_conservation_bot_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservation',
            name='suggest_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
