# Generated by Django 4.2.6 on 2023-10-27 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_remove_content_user_conservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conservation',
            name='user',
        ),
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
