# Generated by Django 4.2.6 on 2023-10-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_conservation_user_content_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservation',
            name='bot_answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conservation',
            name='user_question',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='last_tag',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
