# Generated by Django 4.2.6 on 2023-11-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_conservation_suggest_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservation',
            name='suggest_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
